import { AI_PROVIDER_MAP } from '@/constants'

export const SEARCH_WITH_AI_ROOT_ID = 'MAXAI_SEARCH_WITH_AI_ROOT_ID'
export const SEARCH_WITH_AI_SHADOW_CONTAINER_ID =
  'MAXAI_SEARCH_WITH_AI_SHADOW_CONTAINER_ID'

export const SEARCH_WITH_AI_LOGO_ID = 'SEARCH_WITH_AI_LOGO_ID'

export const SEARCH_WITH_AI_DEFAULT_CRAWLING_LIMIT = 6

export const AI_PROVIDER_NAME_MAP = {
  [AI_PROVIDER_MAP.OPENAI]: 'ChatGPT',
  [AI_PROVIDER_MAP.CLAUDE]: 'Claude',
  [AI_PROVIDER_MAP.BARD]: 'Bard',
  [AI_PROVIDER_MAP.BING]: 'Bing Chat',
  [AI_PROVIDER_MAP.USE_CHAT_GPT_PLUS]: 'MaxAI ChatGPT',
  [AI_PROVIDER_MAP.OPENAI_API]: 'OPENAI_API',
  [AI_PROVIDER_MAP.POE]: 'POE',
  [AI_PROVIDER_MAP.MAXAI_CLAUDE]: 'Claude',
} as const

export * from './searchWithAIPrompt'
