export const ONBOARDING_TOOLTIP_SCENE_TYPES = [
  'CONTEXT_MENU_CTA_BUTTON',
  'FLOATING_CONTEXT_MENU_INPUT_BOX',
  'FLOATING_CONTEXT_MENU_LIST_BOX',
  'FLOATING_CONTEXT_MENU_REPLACE_SELECTION_MENUITEM',
  'FLOATING_CONTEXT_MENU_INPUT_BOX_AFTER_AI_RESPONSE',
  'QUICK_ACCESS_CTA_BUTTON',

  // summary 不区分 gmail、 outlook 之类的
  'EMAIL_SUMMARY_BUTTON',

  'PDF_SUMMARY_BUTTON',

  // ==================== instant reply start ====================
  // instant reply 需要区分不同 社媒场景和使用场景
  // Gmail
  'INSTANT_REPLY__GMAIL__COMPOSE_REPLY_BUTTON',
  'INSTANT_REPLY__GMAIL__COMPOSE_NEW_BUTTON',
  'INSTANT_REPLY__GMAIL__REFINE_DRAFT_BUTTON',

  // Outlook
  'INSTANT_REPLY__OUTLOOK__COMPOSE_REPLY_BUTTON',
  'INSTANT_REPLY__OUTLOOK__COMPOSE_NEW_BUTTON',
  'INSTANT_REPLY__OUTLOOK__REFINE_DRAFT_BUTTON',

  // Twitter
  'INSTANT_REPLY__TWITTER__COMPOSE_REPLY_BUTTON',
  'INSTANT_REPLY__TWITTER__COMPOSE_NEW_BUTTON',
  'INSTANT_REPLY__TWITTER__REFINE_DRAFT_BUTTON',

  // LinkedIn
  'INSTANT_REPLY__LINKEDIN__COMPOSE_REPLY_BUTTON',
  'INSTANT_REPLY__LINKEDIN__COMPOSE_NEW_BUTTON',
  'INSTANT_REPLY__LINKEDIN__REFINE_DRAFT_BUTTON',
  // ==================== instant reply end ====================
] as const
