import { DEFAULT_AI_OUTPUT_LANGUAGE_VALUE } from '@/types'

export const LANGUAGES_OPTIONS = [
  {
    label: 'Auto',
    value: DEFAULT_AI_OUTPUT_LANGUAGE_VALUE,
  },
  {
    label: '简体中文',
    value: 'Simplified Chinese',
  },
  {
    label: '繁體中文',
    value: 'Traditional Chinese',
  },
  {
    label: '日本語',
    value: 'Japanese',
  },
  {
    label: '粵語',
    value: 'Cantonese',
  },
  {
    label: 'Acoli',
    value: 'Acoli',
  },
  {
    label: 'Afrikaans',
    value: 'Afrikaans',
  },
  {
    label: 'Akan',
    value: 'Akan',
  },
  {
    label: 'Aymara',
    value: 'Aymara',
  },
  {
    label: 'azərbaycan',
    value: 'Azerbaijani',
  },
  {
    label: 'Balinese',
    value: 'Balinese',
  },
  {
    label: 'Basa Sunda',
    value: 'Sundanese',
  },
  {
    label: 'Bork, bork, bork!',
    value: 'Chef',
  },
  {
    label: 'bosanski',
    value: 'Bosnian',
  },
  {
    label: 'brezhoneg',
    value: 'Breton',
  },
  {
    label: 'català',
    value: 'Catalan',
  },
  {
    label: 'Cebuano',
    value: 'Cebuano',
  },
  {
    label: 'Čeština',
    value: 'Czech',
  },
  {
    label: 'chiShona',
    value: 'Shona',
  },
  {
    label: 'Corsican',
    value: 'Corsican',
  },
  {
    label: 'Créole haïtien',
    value: 'Haitian Creole',
  },
  {
    label: 'Cymraeg',
    value: 'Welsh',
  },
  {
    label: 'Dansk',
    value: 'Danish',
  },
  {
    label: 'Deutsch',
    value: 'German',
  },
  {
    label: 'Èdè Yorùbá',
    value: 'Yoruba',
  },
  {
    label: 'eesti',
    value: 'Estonian',
  },
  {
    label: 'English',
    value: 'English',
  },
  {
    label: 'Español',
    value: 'Spanish',
  },
  {
    label: 'esperanto',
    value: 'Esperanto',
  },
  {
    label: 'euskara',
    value: 'Basque',
  },
  {
    label: 'Eʋegbe',
    value: 'Ewe',
  },
  {
    label: 'Ewmew Fudd',
    value: 'Elmer Fudd',
  },
  {
    label: 'Filipino',
    value: 'Filipino',
  },
  {
    label: 'føroyskt',
    value: 'Faroese',
  },
  {
    label: 'Français',
    value: 'French',
  },
  {
    label: 'Frysk',
    value: 'Frisian',
  },
  {
    label: 'Ga',
    value: 'Ga',
  },
  {
    label: 'Gaeilge',
    value: 'Irish',
  },
  {
    label: 'Gàidhlig',
    value: 'Scottish Gaelic',
  },
  {
    label: 'galego',
    value: 'Galician',
  },
  {
    label: 'Guarani',
    value: 'Guarani',
  },
  {
    label: 'Hausa',
    value: 'Hausa',
  },
  {
    label: 'Hrvatski',
    value: 'Croatian',
  },
  {
    label: 'ʻŌlelo Hawaiʻi',
    value: 'Hawaiian',
  },
  {
    label: 'Ichibemba',
    value: 'Bemba',
  },
  {
    label: 'Igbo',
    value: 'Igbo',
  },
  {
    label: 'Ikirundi',
    value: 'Kirundi',
  },
  {
    label: 'Indonesia',
    value: 'Indonesian',
  },
  {
    label: 'interlingua',
    value: 'Interlingua',
  },
  {
    label: 'IsiXhosa',
    value: 'Xhosa',
  },
  {
    label: 'isiZulu',
    value: 'Zulu',
  },
  {
    label: 'íslenska',
    value: 'Icelandic',
  },
  {
    label: 'Italiano',
    value: 'Italian',
  },
  {
    label: 'Jawa',
    value: 'Javanese',
  },
  {
    label: 'Kinyarwanda',
    value: 'Kinyarwanda',
  },
  {
    label: 'Kiswahili',
    value: 'Swahili',
  },
  {
    label: 'Klingon',
    value: 'Klingon',
  },
  {
    label: 'Kongo',
    value: 'Kongo',
  },
  {
    label: 'kreol morisien',
    value: 'Mauritian Creole',
  },
  {
    label: 'Krio',
    value: 'Krio',
  },
  {
    label: 'kurdî',
    value: 'Kurdish',
  },
  {
    label: 'Latin',
    value: 'Latin',
  },
  {
    label: 'latviešu',
    value: 'Latvian',
  },
  {
    label: 'lea fakatonga',
    value: 'Tongan',
  },
  {
    label: 'lietuvių',
    value: 'Lithuanian',
  },
  {
    label: 'lingála',
    value: 'Lingala',
  },
  {
    label: 'Lozi',
    value: 'Lozi',
  },
  {
    label: 'Luba-Lulua',
    value: 'Luba-Lulua',
  },
  {
    label: 'Luganda',
    value: 'Luganda',
  },
  {
    label: 'magyar',
    value: 'Hungarian',
  },
  {
    label: 'Malagasy',
    value: 'Malagasy',
  },
  {
    label: 'Malti',
    value: 'Maltese',
  },
  {
    label: 'Māori',
    value: 'Māori',
  },
  {
    label: 'Melayu',
    value: 'Malay',
  },
  {
    label: 'Naijíriá Píjin',
    value: 'Nigerian Pidgin',
  },
  {
    label: 'Nederlands',
    value: 'Dutch',
  },
  {
    label: 'norsk',
    value: 'Norwegian',
  },
  {
    label: 'norsk nynorsk',
    value: 'Norwegian Nynorsk',
  },
  {
    label: 'Northern Sotho',
    value: 'Northern Sotho',
  },
  {
    label: 'Nyanja',
    value: 'Nyanja',
  },
  {
    label: 'o‘zbek',
    value: 'Uzbek',
  },
  {
    label: 'Occitan',
    value: 'Occitan',
  },
  {
    label: 'Oromoo',
    value: 'Oromo',
  },
  {
    label: 'Pirate',
    value: 'Pirate',
  },
  {
    label: 'polski',
    value: 'Polish',
  },
  {
    label: 'Português',
    value: 'Portuguese',
  },
  {
    label: 'română',
    value: 'Romanian',
  },
  {
    label: 'rumantsch',
    value: 'Romansh',
  },
  {
    label: 'Runasimi',
    value: 'Quechua',
  },
  {
    label: 'Runyankore',
    value: 'Runyankore',
  },
  {
    label: 'Seselwa Creole French',
    value: 'Seychellois Creole',
  },
  {
    label: 'shqip',
    value: 'Albanian',
  },
  {
    label: 'Slovenčina',
    value: 'Slovak',
  },
  {
    label: 'slovenščina',
    value: 'Slovenian',
  },
  {
    label: 'Soomaali',
    value: 'Somali',
  },
  {
    label: 'Southern Sotho',
    value: 'Southern Sotho',
  },
  {
    label: 'srpski (latinica)',
    value: 'Serbian (Latin)',
  },
  {
    label: 'Suomi',
    value: 'Finnish',
  },
  {
    label: 'Svenska',
    value: 'Swedish',
  },
  {
    label: 'Tiếng Việt',
    value: 'Vietnamese',
  },
  {
    label: 'Tswana',
    value: 'Tswana',
  },
  {
    label: 'Tumbuka',
    value: 'Tumbuka',
  },
  {
    label: 'Türkçe',
    value: 'Turkish',
  },
  {
    label: 'türkmen dili',
    value: 'Turkmen',
  },
  {
    label: 'Wolof',
    value: 'Wolof',
  },
  {
    label: 'Ελληνικά',
    value: 'Greek',
  },
  {
    label: 'беларуская',
    value: 'Belarusian',
  },
  {
    label: 'български',
    value: 'Bulgarian',
  },
  {
    label: 'кыргызча',
    value: 'Kyrgyz',
  },
  {
    label: 'қазақ тілі',
    value: 'Kazakh',
  },
  {
    label: 'македонски',
    value: 'Macedonian',
  },
  {
    label: 'монгол',
    value: 'Mongolian',
  },
  {
    label: 'Русский',
    value: 'Russian',
  },
  {
    label: 'српски',
    value: 'Serbian',
  },
  {
    label: 'татар',
    value: 'Tatar',
  },
  {
    label: 'тоҷикӣ',
    value: 'Tajik',
  },
  { label: 'Українська', value: 'Ukrainian' },
  {
    label: 'ქართული',
    value: 'Georgian',
  },
  {
    label: 'հայերեն',
    value: 'Armenian',
  },
  {
    label: 'ייִדיש',
    value: 'Yiddish',
  },
  {
    label: 'עברית',
    value: 'Hebrew',
  },
  {
    label: 'ئۇيغۇرچە',
    value: 'Uighur',
  },
  {
    label: 'اردو',
    value: 'Urdu',
  },
  {
    label: 'العربية',
    value: 'Arabic',
  },
  {
    label: 'پښتو',
    value: 'Pashto',
  },
  {
    label: 'سنڌي',
    value: 'Sindhi',
  },
  {
    label: 'فارسی',
    value: 'Persian',
  },
  {
    label: 'کوردیی ناوەندی',
    value: 'Central Kurdish',
  },
  {
    label: 'ትግርኛ',
    value: 'Tigrinya',
  },
  {
    label: 'አማርኛ',
    value: 'Amharic',
  },
  {
    label: 'नेपाली',
    value: 'Nepali',
  },
  {
    label: 'भोजपुरी',
    value: 'Bhojpuri',
  },
  {
    label: 'मराठी',
    value: 'Marathi',
  },
  {
    label: 'संस्कृत भाषा',
    value: 'Sanskrit',
  },
  {
    label: 'हिन्दी',
    value: 'Hindi',
  },
  {
    label: 'অসমীয়া',
    value: 'Assamese',
  },
  {
    label: 'বাংলা',
    value: 'Bengali',
  },
  {
    label: 'ਪੰਜਾਬੀ',
    value: 'Punjabi',
  },
  {
    label: 'ગુજરાતી',
    value: 'Gujarati',
  },
  {
    label: 'ଓଡ଼ିଆ',
    value: 'Odia',
  },
  {
    label: 'தமிழ்',
    value: 'Tamil',
  },
  {
    label: 'తెలుగు',
    value: 'Telugu',
  },
  {
    label: 'ಕನ್ನಡ',
    value: 'Kannada',
  },
  {
    label: 'മലയാളം',
    value: 'Malayalam',
  },
  {
    label: 'සිංහල',
    value: 'Sinhala',
  },
  {
    label: 'ไทย',
    value: 'Thai',
  },
  {
    label: 'ລາວ',
    value: 'Lao',
  },
  {
    label: 'မြန်မာ',
    value: 'Burmese',
  },
  {
    label: 'ខ្មែរ',
    value: 'Khmer',
  },
  {
    label: 'ᏣᎳᎩ',
    value: 'Cherokee',
  },
  {
    label: '한국어',
    value: 'Korean',
  },
  {
    label: '0|\\\\/|G |-|4xx0|2 !!!!111',
    value: 'Leet Speak',
  },
]

export const COUNTRIES_MAP: Map<string, string> = new Map(
  Object.entries({
    Andorra: 'ad',
    'United Arab Emirates': 'ae',
    Afghanistan: 'af',
    'Antigua and Barbuda': 'ag',
    Anguilla: 'ai',
    Albania: 'al',
    Armenia: 'am',
    Angola: 'ao',
    Antarctica: 'aq',
    Argentina: 'ar',
    'American Samoa': 'as',
    Austria: 'at',
    Australia: 'au',
    Aruba: 'aw',
    'Åland Islands': 'ax',
    Azerbaijan: 'az',
    'Bosnia and Herzegovina': 'ba',
    Barbados: 'bb',
    Bangladesh: 'bd',
    Belgium: 'be',
    'Burkina Faso': 'bf',
    Bulgaria: 'bg',
    Bahrain: 'bh',
    Burundi: 'bi',
    Benin: 'bj',
    'Saint Barthélemy': 'bl',
    Bermuda: 'bm',
    Brunei: 'bn',
    Bolivia: 'bo',
    'Caribbean Netherlands': 'bq',
    Brazil: 'br',
    Bahamas: 'bs',
    Bhutan: 'bt',
    'Bouvet Island': 'bv',
    Botswana: 'bw',
    Belarus: 'by',
    Belize: 'bz',
    Canada: 'ca',
    'Cocos (Keeling) Islands': 'cc',
    'DR Congo': 'cd',
    'Congo, the Democratic Republic of the': 'cd',
    'Democratic Republic of the Congo': 'cd',
    'Central African Republic': 'cf',
    'Republic of the Congo': 'cg',
    Switzerland: 'ch',
    "Côte d'Ivoire (Ivory Coast)": 'ci',
    'Cook Islands': 'ck',
    Chile: 'cl',
    Cameroon: 'cm',
    China: 'cn',
    Colombia: 'co',
    'Costa Rica': 'cr',
    Cuba: 'cu',
    'Cape Verde': 'cv',
    Curaçao: 'cw',
    'Christmas Island': 'cx',
    Cyprus: 'cy',
    Czechia: 'cz',
    'Czech Republic': 'cz',
    Germany: 'de',
    Djibouti: 'dj',
    Denmark: 'dk',
    Dominica: 'dm',
    'Dominican Republic': 'do',
    Algeria: 'dz',
    Ecuador: 'ec',
    Estonia: 'ee',
    Egypt: 'eg',
    'Western Sahara': 'eh',
    Eritrea: 'er',
    Spain: 'es',
    Ethiopia: 'et',
    'European Union': 'eu',
    Finland: 'fi',
    Fiji: 'fj',
    'Falkland Islands': 'fk',
    Micronesia: 'fm',
    'Faroe Islands': 'fo',
    France: 'fr',
    Gabon: 'ga',
    'United Kingdom': 'gb',
    England: 'gb-eng',
    'Northern Ireland': 'gb-nir',
    Scotland: 'gb-sct',
    Wales: 'gb-wls',
    Grenada: 'gd',
    Georgia: 'us-ga',
    'French Guiana': 'gf',
    Guernsey: 'gg',
    Ghana: 'gh',
    Gibraltar: 'gi',
    Greenland: 'gl',
    Gambia: 'gm',
    Guinea: 'gn',
    Guadeloupe: 'gp',
    'Equatorial Guinea': 'gq',
    Greece: 'gr',
    'South Georgia': 'gs',
    Guatemala: 'gt',
    Guam: 'gu',
    'Guinea-Bissau': 'gw',
    Guyana: 'gy',
    'Hong Kong': 'hk',
    'Heard Island and McDonald Islands': 'hm',
    Honduras: 'hn',
    Croatia: 'hr',
    Haiti: 'ht',
    Hungary: 'hu',
    Indonesia: 'id',
    Ireland: 'ie',
    Israel: 'il',
    'Isle of Man': 'im',
    India: 'in',
    'British Indian Ocean Territory': 'io',
    Iraq: 'iq',
    Iran: 'ir',
    Iceland: 'is',
    Italy: 'it',
    Jersey: 'je',
    Jamaica: 'jm',
    Jordan: 'jo',
    Japan: 'jp',
    Kenya: 'ke',
    Kyrgyzstan: 'kg',
    Cambodia: 'kh',
    Kiribati: 'ki',
    Comoros: 'km',
    'Saint Kitts and Nevis': 'kn',
    'North Korea': 'kp',
    'South Korea': 'kr',
    'Korea, Republic of': 'kr',
    Kuwait: 'kw',
    'Cayman Islands': 'ky',
    Kazakhstan: 'kz',
    Laos: 'la',
    Lebanon: 'lb',
    'Saint Lucia': 'lc',
    Liechtenstein: 'li',
    'Sri Lanka': 'lk',
    Liberia: 'lr',
    Lesotho: 'ls',
    Lithuania: 'lt',
    Luxembourg: 'lu',
    Latvia: 'lv',
    Libya: 'ly',
    Morocco: 'ma',
    Monaco: 'mc',
    Moldova: 'md',
    Montenegro: 'me',
    'Saint Martin': 'mf',
    Madagascar: 'mg',
    'Marshall Islands': 'mh',
    'North Macedonia': 'mk',
    Mali: 'ml',
    Myanmar: 'mm',
    Mongolia: 'mn',
    Macau: 'mo',
    'Northern Mariana Islands': 'mp',
    Martinique: 'mq',
    Mauritania: 'mr',
    Montserrat: 'ms',
    Malta: 'mt',
    Mauritius: 'mu',
    Maldives: 'mv',
    Malawi: 'mw',
    Mexico: 'mx',
    Malaysia: 'my',
    Mozambique: 'mz',
    Namibia: 'na',
    'New Caledonia': 'nc',
    Niger: 'ne',
    'Norfolk Island': 'nf',
    Nigeria: 'ng',
    Nicaragua: 'ni',
    Netherlands: 'nl',
    Norway: 'no',
    Nepal: 'np',
    Nauru: 'nr',
    Niue: 'nu',
    'New Zealand': 'nz',
    Oman: 'om',
    Panama: 'pa',
    Peru: 'pe',
    'French Polynesia': 'pf',
    'Papua New Guinea': 'pg',
    Philippines: 'ph',
    Pakistan: 'pk',
    Poland: 'pl',
    'Saint Pierre and Miquelon': 'pm',
    'Pitcairn Islands': 'pn',
    'Puerto Rico': 'pr',
    Palestine: 'ps',
    Portugal: 'pt',
    Palau: 'pw',
    Paraguay: 'py',
    Qatar: 'qa',
    Réunion: 're',
    Romania: 'ro',
    Serbia: 'rs',
    Russia: 'ru',
    Rwanda: 'rw',
    'Saudi Arabia': 'sa',
    'Solomon Islands': 'sb',
    Seychelles: 'sc',
    Sudan: 'sd',
    Sweden: 'se',
    Singapore: 'sg',
    'Saint Helena, Ascension and Tristan da Cunha': 'sh',
    Slovenia: 'si',
    'Svalbard and Jan Mayen': 'sj',
    Slovakia: 'sk',
    'Sierra Leone': 'sl',
    'San Marino': 'sm',
    Senegal: 'sn',
    Somalia: 'so',
    Suriname: 'sr',
    'South Sudan': 'ss',
    'São Tomé and Príncipe': 'st',
    'El Salvador': 'sv',
    'Sint Maarten': 'sx',
    Syria: 'sy',
    'Eswatini (Swaziland)': 'sz',
    'Turks and Caicos Islands': 'tc',
    Chad: 'td',
    'French Southern and Antarctic Lands': 'tf',
    Togo: 'tg',
    Thailand: 'th',
    Tajikistan: 'tj',
    Tokelau: 'tk',
    'Timor-Leste': 'tl',
    Turkmenistan: 'tm',
    Tunisia: 'tn',
    Tonga: 'to',
    Turkey: 'tr',
    'Trinidad and Tobago': 'tt',
    Tuvalu: 'tv',
    Taiwan: 'cn',
    Tanzania: 'tz',
    Ukraine: 'ua',
    Uganda: 'ug',
    'United States Minor Outlying Islands': 'um',
    'United Nations': 'un',
    'United States': 'us',
    Alaska: 'us-ak',
    Alabama: 'us-al',
    Arkansas: 'us-ar',
    Arizona: 'us-az',
    California: 'us-ca',
    Colorado: 'us-co',
    Connecticut: 'us-ct',
    Delaware: 'us-de',
    Florida: 'us-fl',
    Hawaii: 'us-hi',
    Iowa: 'us-ia',
    Idaho: 'us-id',
    Illinois: 'us-il',
    Indiana: 'us-in',
    Kansas: 'us-ks',
    Kentucky: 'us-ky',
    Louisiana: 'us-la',
    Massachusetts: 'us-ma',
    Maryland: 'us-md',
    Maine: 'us-me',
    Michigan: 'us-mi',
    Minnesota: 'us-mn',
    Missouri: 'us-mo',
    Mississippi: 'us-ms',
    Montana: 'us-mt',
    'North Carolina': 'us-nc',
    'North Dakota': 'us-nd',
    Nebraska: 'us-ne',
    'New Hampshire': 'us-nh',
    'New Jersey': 'us-nj',
    'New Mexico': 'us-nm',
    Nevada: 'us-nv',
    'New York': 'us-ny',
    Ohio: 'us-oh',
    Oklahoma: 'us-ok',
    Oregon: 'us-or',
    Pennsylvania: 'us-pa',
    'Rhode Island': 'us-ri',
    'South Carolina': 'us-sc',
    'South Dakota': 'us-sd',
    Tennessee: 'us-tn',
    Texas: 'us-tx',
    Utah: 'us-ut',
    Virginia: 'us-va',
    Vermont: 'us-vt',
    Washington: 'us-wa',
    Wisconsin: 'us-wi',
    'West Virginia': 'us-wv',
    Wyoming: 'us-wy',
    Uruguay: 'uy',
    Uzbekistan: 'uz',
    'Vatican City (Holy See)': 'va',
    'Saint Vincent and the Grenadines': 'vc',
    Venezuela: 've',
    'British Virgin Islands': 'vg',
    'United States Virgin Islands': 'vi',
    Vietnam: 'vn',
    Vanuatu: 'vu',
    'Wallis and Futuna': 'wf',
    Samoa: 'ws',
    Kosovo: 'xk',
    Yemen: 'ye',
    Mayotte: 'yt',
    'South Africa': 'za',
    Zambia: 'zm',
    Zimbabwe: 'zw',
  }),
)
